# Generated by Django 5.1.4 on 2024-12-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('weight', models.CharField(max_length=50)),
                ('temperament', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('life_span', models.CharField(max_length=50)),
                ('adaptability', models.IntegerField()),
                ('affection_level', models.IntegerField()),
                ('energy_level', models.IntegerField()),
                ('health_issues', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('stranger_friendly', models.IntegerField()),
                ('child_friendly', models.IntegerField()),
                ('hairless', models.BooleanField()),
                ('natural', models.BooleanField()),
                ('short_legs', models.BooleanField()),
                ('rare', models.BooleanField()),
                ('indoor', models.BooleanField()),
                ('image', models.URLField()),
                ('wikipedia_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('temperament', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('life_span', models.CharField(max_length=50)),
                ('bred_for', models.CharField(max_length=255)),
                ('image', models.URLField()),
            ],
        ),
    ]
